[build]
  base = "."
  publish = "dist/spa"
  command = "yarn build"

[[edge_functions]]
  function = "handleRequestPage"
  path = "/r/*"

[functions]
  included_files = [
    "netlify/edge-functions/lib/**",
    "src/lib/**.ts"
  ]

[[redirects]]
  from = "/.netlify/images"
  status = 404
  force = true
  conditions = { Query = ["url"] }

[[redirects]]
  from = "/blog/*"
  to = "https://fiddl.art/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[images]
  remote_images = ["https://api.fiddl.art/images/.*","https://api.fiddl.art/avatars/.*"]


