[build]
  base = "."
  publish = "dist/spa"
  command = "yarn build"
[dev]
  command = "yarn dev --port 5173"

[[edge_functions]]
  function = "datafast"
  path     = "/js/script.js"
  cache    = "manual"

[[edge_functions]]
  function = "datafast"
  path     = "/js/script.hash.js"
  cache    = "manual"

[[edge_functions]]
  function = "datafast"
  path     = "/api/events"
  cache    = "manual"

[[edge_functions]]
  function = "request"
  path = "/request/*"
  cache = "manual"

[[edge_functions]]
  function = "model"
  path     = "/model/:modelName/:customModelId?"
  cache = "manual"

[[edge_functions]]
  function = "models"
  path     = "/models/:filterTag?"
  cache = "manual"

[[edge_functions]]
  function = "browse"
  path     = "/browse"
  cache = "manual"

[[edge_functions]]
  function = "missions"
  path     = "/missions"
  cache = "manual"

[[edge_functions]]
  function = "events"
  path     = "/events"
  cache = "manual"

[[edge_functions]]
  function = "profile"
  path     = "/@:username"
  cache = "manual"

[[edge_functions]]
  function = "magicMirror"
  path     = "/magicMirror"
  cache = "manual"

[[edge_functions]]
  function = "claim"
  path     = "/claim/*"
  cache = "manual"

[[edge_functions]]
  function = "forge"
  path     = "/forge/:mode?"
  cache = "manual"

[[edge_functions]]
  function = "studio"
  path     = "/studio"
  cache = "manual"

[[edge_functions]]
  function = "tos"
  path     = "/tos"
  cache = "manual"

[[edge_functions]]
  function = "index"
  path     = "/"
  cache = "manual"

[[edge_functions]]
  function = "sitemap"
  path     = "/sitemap.xml"
  cache = "manual"

[[edge_functions]]
  function = "sitemap"
  path     = "/sitemap-static.xml"
  cache = "manual"

[[edge_functions]]
  function = "sitemap"
  path     = "/sitemap-requests-images.xml"
  cache = "manual"

[[edge_functions]]
  function = "sitemap"
  path     = "/sitemap-requests-videos.xml"
  cache = "manual"

[functions]
  included_files = [
    "netlify/edge-functions/lib/**",
  ]


[[redirects]]
  from = "/blog/*"
  to = "https://fiddl.art/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[images]
  remote_images = ["https://api.fiddl.art/images/.*","https://api.fiddl.art/avatars/.*"]
