[build]
  base = "."
  publish = "dist/spa"
  command = "yarn build"
[dev]
  command = "yarn dev --port 5173"

[[edge_functions]]
  function = "routes/request"
  path = "/r/*"
  cache = "manual"

[[edge_functions]]
  function = "routes/model"
  path     = "/model/:modelName/:customModelId?"
  cache = "manual"

[functions]
  included_files = [
    "netlify/edge-functions/lib/**",
  ]
  deno_import_map = "netlify/edge-functions/import_map.json"


[[redirects]]
  from = "/blog/*"
  to = "https://fiddl.art/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[images]
  remote_images = ["https://api.fiddl.art/images/.*","https://api.fiddl.art/avatars/.*"]



