[build]
  base = "."
  publish = "dist/ssg"
  command = "yarn build:ssg"

[[edge_functions]]
  function = "handleRequestPage"
  path = "/r/*"

[functions]
  included_files = ["netlify/edge-functions/lib/**"]

[[redirects]]
  from = "/blog/*"
  to = "https://fiddl-blog.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://api.fiddl.art/images/.*","https://api.fiddl.art/avatars/.*"]


