[build]
  base = "."
  publish = "dist/spa"
  command = "yarn build"
[dev]
  command = "yarn dev --port 5173"

[[edge_functions]]
  function = "request"
  path = "/request/*"
  cache = "manual"

[[edge_functions]]
  function = "model"
  path     = "/model/:modelName/:customModelId?"
  cache = "manual"

[[edge_functions]]
  function = "models"
  path     = "/models/:filterTag?"
  cache = "manual"

[[edge_functions]]
  function = "browse"
  path     = "/browse"
  cache = "manual"

[[edge_functions]]
  function = "missions"
  path     = "/missions"
  cache = "manual"

[[edge_functions]]
  function = "profile"
  path     = "/@:username"
  cache = "manual"

[[edge_functions]]
  function = "magicMirror"
  path     = "/magicMirror"
  cache = "manual"

[[edge_functions]]
  function = "index"
  path     = "/"
  cache = "manual"

[functions]
  included_files = [
    "netlify/edge-functions/lib/**",
  ]


[[redirects]]
  from = "/blog/*"
  to = "https://fiddl.art/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[images]
  remote_images = ["https://api.fiddl.art/images/.*","https://api.fiddl.art/avatars/.*"]



