[build]
  base = "."
  publish = "dist/spa"
  command = "yarn build"
  # functions = "netlify/functions/dist"

[[edge_functions]]
  function = "handleRequestPage"
  path = "/r/*"

# [[redirects]]
#   from = "/r/*"
#   to = "/.netlify/functions/renderMetadata"
#   status = 200
#   force = true

[[redirects]]
  from = "https://alpha.fiddl.art/*"
  to = "https://fiddl.art/:splat"
  status = 301
  force = true

[images]
  remote_images = ["https://api.fiddl.art/images/.*"]
