[build]
  base = "."
  publish = "dist/spa"
  command = "yarn build"
  functions = "netlify/functions/dist"

[[redirects]]
  # Route bots to the function for metadata rendering
  from = "/r/*"
  to = "/.netlify/functions/renderMetadata"
  status = 200
  force = true
  conditions = { User-Agent = "Googlebot|Bingbot|Twitterbot|facebookexternalhit|LinkedInBot|TelegramBot|WhatsApp|Slackbot|Discordbot|Pinterest" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://api.fiddl.art/images/.*"]
